### ISSUE TITLE
PART vs Chapter

### ISSUE THREAD

**Issue by jmaferreira** [DILCISBoard/E-ARK-CSIP#240]
Should we use the terminology Part or Chapter?
@DrJaime any suggestions?

**Comment by karinbredenberg** [comment]
Part I would say.

**Comment by DrJaime** [comment]
Hi Miguel,

In this instance we should use Part rather than Chapter. There is no
industry consistency on the subject. Some specifications and standards use
Part, some use Chapter and others use neither. This is a grey area to say
the least, but Chapter is associated with a book whereas this is more of a
document ... so Part is more appropriate.

Best wishes,


Jaime


On 17 Dec 2018 11:58 am, "Miguel Ferreira" <notifications@github.com> wrote:

Should we use the terminology Part or Chapter?
@DrJaime <https://github.com/DrJaime> any suggestions?

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/DILCISBoard/E-ARK-CSIP/issues/240>, or mute the thread

**Comment by jmaferreira** [comment]
Ok. You're the man! :)
