### ISSUE TITLE
CSIPSTR4 and CSIPSTR12: metadata vs packaging information

### ISSUE THREAD

**Issue by jmaferreira** [DILCISBoard/E-ARK-CSIP#250]
METS is referenced as "metadata". I tend to think of it more in terms of "packaging information".

**Comment by karinbredenberg** [comment]
Tricky one since METS is for describing the metadata. (The Metadata Encoding and Transmission Standard  (METS) is a data encoding and transmission specification, expressed in XML, that provides the means to convey the metadata necessary for both the management of digital objects within a repository and the exchange of such objects between repositories (or between repositories and their users).)

**Comment by PhillipTommerholt** [comment]
In the DIP specification we call it "structural metadata"
