### ISSUE TITLE
Appendix C: A Full List of E-ARK CSIP Requirements (the list is not full)

### ISSUE THREAD

**Issue by PhillipTommerholt** [DILCISBoard/E-ARK-CSIP#374]
The list in Appendix C is not the full list. Only requirements for the METS.xml

**Comment by carlwilson** [comment]
The issue is that the principles aren't in the METS profile which is what's used to generate this table. Will implement a fix but will need to split [the principles index file first](https://github.com/DILCISBoard/E-ARK-CSIP/blob/master/specification/specification/principles/index.md) to ensure that they're standalone suitable for inclusion.
