### ISSUE TITLE
Redundancies and incompatible priority levels

### ISSUE THREAD

**Issue by shsdev** [DILCISBoard/E-ARK-CSIP#570]
Some rules in the CSIP are difficult to follow by implementers because they have the same path specification ("Name & Loc") but different descriptions ("Description & usage"). Additionally, some of them seem to have incompatible priority levels. 

CSIP88/CSIP90: both rules apply to the same node:

    mets/structMap[@LABEL='CSIP']/div/div[@LABEL='Metadata']

In both cases it is checked if there is a division with the label "Metadata". 

The same applies to CSIP93/CSIP95 for the 'Documentation' label:

    mets/structMap[@LABEL='CSIP']/div/div[@LABEL='Documentation']

In this case it is more confusing because CSIP93 is 'SHOULD' and CSIP95 is 'MUST'.

The same applies to CSIP97/CSIP99 for the 'Schemas' label:

    mets/structMap[@LABEL='CSIP']/div/div[@LABEL='Schemas']

The same applies to CSIP101 /CSIP103 for the 'Representations' label:

mets/structMap[@LABEL='CSIP']/div/div[@LABEL='Representations']

In this case it is more confusing because CSIP101 is 'SHOULD' and CSIP103 is 'MUST'.

**Comment by karinbredenberg** [comment]
The two requirements for these attributes reflect a desire to keep the requirements atomic, i.e. to not bundle multiple checks into a single requirement. In each case the first requirement defines whether the division itself is mandatory, the second defines the required label value. If the first requirement is fulfilled and the division is present the LABEL attribute must have the given value. While there is some redundancy across the requirements we believe that they're not contradictory, i.e. the MUSTs only apply when the SHOULDs are met. While we're open to optimising these requirements, perhaps using xQuery rather than xPath to state the location, any action would be for a new minor version release. We're currently only addressing minor issues, e.g. typos and typography.

**Comment by shsdev** [comment]
Sure. Just to keep in mind that this logic should be explained more clearly.

This is the feedback from an implementer without prior experience with E-ARK standards. If they say that they have difficulties understanding this, then others might do so as well.

**Comment by karinbredenberg** [comment]
A clear thing to add to the guide line.

**Comment by PhillipTommerholt** [comment]
I am currently trying to create a testCase.xml for the validation tool. What is the requirement in CSIP88 which is not identical with the requirement in CSIP90? For me they look like the same: there MUST be a div-element with the @LABEL='metadata' nested in the div-element with the @LABEL='CSIP'. 

When I try to find the guideline I find https://dilcis.eu/images/2020review/1_Draft_Guideline_IP.pdf for IPs in general and the guideline stops with the CSIPSTR16 and does not include the METS requirements. Where will I (if possible) be able to find further detailed explanations to the METS requirements?

**Comment by karinbredenberg** [comment]
Not all requirements will be explained in the guideline. The ones mentioned in the OP post are being explained in the guideline for IP's. CSIP88 and CSIP90 is described in the version that have been looked at. Clarifications will be made in the headings.

**Comment by karinbredenberg** [comment]
This is explained in the published guideline.
