### ISSUE TITLE
CSIP114 conflicts with its examples

### ISSUE THREAD

**Issue by koit** [DILCISBoard/E-ARK-CSIP#642]
[CSIP114](https://earkcsip.dilcis.eu/#CSIP114) requires the presence of one or more `mets/fileSec/fileGrp/@USE` attributes with the value "Representations," i.e.:

USE="Representations"

However, the examples use more detailed values, e.g.:

USE="Representations/submission/data"
USE="Representations/preingest"
USE="Representations/submission"
USE="Representations/ingest"

Either the requirement text or the examples need to be changed.

**Comment by karinbredenberg** [comment]
Looks like there are text gone missing. The use starts with representations and the folder of what it is is given. But we cant put the rest of the value in the requirement just the start. Textual update will come in the next version.

**Comment by hsilva-keep** [comment]
@karinbredenberg All structMap representation LABEL related requirements have the same problem (CSIP101-CSIP104 and CSIP119). 

So, the ideia is to assume that in both cases the logic is the same: the value starts with "Representations" and the whole value should be the path to the representation or representation data (like CSIP64 mentions)? Because if so, that logic colides with CSIPSTR13, which states that the folder name is "representation" (vs. "Representation").
